# Synthetic expression cases: filters, tests, operators. Jinja source text exactly as Jinja sees it.
VARS = {
    "path_tpl": "/srv/roles/demo_agent/templates/config-base.conf.j2",
    "s": "Hello World",
    "s_pad": "  padded \n",
    "csv": "a,b,,c",
    "n": 7, "f": 2.5, "neg": -7,
    "b_true": True, "b_str_yes": "yes", "b_str_false": "False",
    "none_v": None,
    "empty_s": "", "empty_l": [], "empty_d": {},
    "lst": [3, 1, 2, 3],
    "strs": ["b", "a", "C"],
    "users": [
        {"name": "alice", "uid": 1001, "groups": ["adm", "dev"], "enabled": True},
        {"name": "bob", "uid": 1002, "groups": ["dev"], "enabled": False},
        {"name": "carol", "uid": 1000, "enabled": True},
    ],
    "d": {"b": 2, "a": 1},
    "nested1": {"a": {"x": 1, "l": [1, 2]}, "k": "v1"},
    "nested2": {"a": {"y": 2, "l": [3]}, "k": "v2"},
    "cidr": "192.0.2.10/24",
    "multi": "line1\nline2\n\nline4",
    "multi_nl": "line1\nline2\n",
    "tmpl_var": "{{ s }} indirect",
    "unicode_s": "Grüße",
    "int_str": "42", "float_str": "3.14", "bad_int": "4x",
    "b64": "aGVsbG8=",
    "ver": "2.10.1",
}

CASES = [
    # --- path filters ---
    ("basename1", r"path_tpl | basename"),
    ("basename_trailing", r"'/a/b/' | basename"),
    ("dirname1", r"path_tpl | dirname"),
    ("dirname_root", r"'/a' | dirname"),
    ("dirname_rel", r"'file.txt' | dirname"),
    ("splitext1", r"path_tpl | basename | splitext"),
    ("splitext_first", r"path_tpl | basename | ansible.builtin.splitext | first"),
    ("splitext_noext", r"'Makefile' | splitext"),
    ("splitext_dotfile", r"'.bashrc' | splitext"),
    # --- the user's example (Jinja text after YAML unescape of '\\.j2$') ---
    ("user_example", r"path_tpl | basename | regex_replace('^config-', '') | regex_replace('\.j2$', '')"),
    ("user_example_dbl", r"path_tpl | basename | regex_replace('^config-', '') | regex_replace('\\.j2$', '')"),
    ("user_example_nodot", r"path_tpl | basename | regex_replace('^config-', '') | regex_replace('.j2$', '')"),
    # --- regex_replace ---
    ("rr_backref_dbl", r"'abc-123' | regex_replace('(\\w+)-(\\d+)', '\\2_\\1')"),
    ("rr_backref_single", r"'abc-123' | regex_replace('(\w+)-(\d+)', '\2_\1')"),
    ("rr_named", r"'abc-123' | regex_replace('(?P<w>\\w+)-(?P<n>\\d+)', '\\g<n>:\\g<w>')"),
    ("rr_group0", r"'abc' | regex_replace('b', '[\\g<0>]')"),
    ("rr_dollar_repl", r"'abc' | regex_replace('(b)', '$1')"),
    ("rr_bad_group", r"'abc' | regex_replace('b', '\\3')"),
    ("rr_icase", r"'ABC abc' | regex_replace('abc', 'x', ignorecase=true)"),
    ("rr_multiline", r"multi | regex_replace('^line', 'L', multiline=true)"),
    ("rr_nomultiline", r"multi | regex_replace('^line', 'L')"),
    ("rr_count", r"'aaa' | regex_replace('a', 'b', count=2)"),
    ("rr_dollar_end", r"multi_nl | regex_replace('$', '!')"),
    ("rr_bigZ", r"'a\n' | regex_replace('a\\Z', 'x')"),
    ("rr_empty_match", r"'abc' | regex_replace('x*', '-')"),
    ("rr_unicode_w", r"unicode_s | regex_replace('\\w', '_')"),
    ("rr_lookbehind", r"'foo.j2' | regex_replace('(?<=foo)\\.j2', '')"),
    ("rr_named_backref_pattern", r"'abab' | regex_replace('(?P<x>ab)(?P=x)', 'Y')"),
    ("rr_nonstr_input", r"123 | regex_replace('2', 'x')"),
    ("rr_list_input", r"lst | regex_replace('1', 'x')"),
    ("rr_none_input", r"none_v | regex_replace('o', 'x')"),
    ("rr_newline_escape", r"'a b' | regex_replace(' ', '\n')"),
    ("rr_repl_backslash_n", r"'a b' | regex_replace(' ', '\\n')"),
    # --- regex_search / findall / tests ---
    ("rs_basic", r"'abc-123' | regex_search('\\d+')"),
    ("rs_nomatch", r"'abc' | regex_search('\\d+')"),
    ("rs_group", r"'abc-123' | regex_search('(\\w+)-(\\d+)', '\\2')"),
    ("rs_named", r"'abc-123' | regex_search('(?P<n>\\d+)', '\\g<n>')"),
    ("rs_nomatch_group", r"'abc' | regex_search('(\\d+)', '\\1')"),
    ("rfa_basic", r"'a1b22' | regex_findall('\\d+')"),
    ("rfa_groups", r"'k1=v1 k2=v2' | regex_findall('(\\w+)=(\\w+)')"),
    ("rescape", r"'a.b*c' | regex_escape"),
    ("t_match", r"'abc' is match('b')"),
    ("t_search", r"'abc' is search('b')"),
    ("t_regex", r"'abc' is regex('b')"),
    ("t_match_anchor", r"'abc' is match('a.c$')"),
    # --- replace ---
    ("replace1", r"s | replace('o', '0')"),
    ("replace_count", r"s | replace('o', '0', 1)"),
    ("replace_method", r"s.replace('o', '0')"),
    ("replace_regexchars", r"'a.b' | replace('.', '-')"),
    # --- default ---
    ("def_undef", r"undefined_x | default('d')"),
    ("def_none", r"none_v | default('d')"),
    ("def_empty", r"empty_s | default('d')"),
    ("def_empty_true", r"empty_s | default('d', true)"),
    ("def_false_true", r"false | default('d', true)"),
    ("def_zero_true", r"0 | default('d', true)"),
    ("def_none_true", r"none_v | default('d', true)"),
    ("def_emptylist_true", r"empty_l | default(['x'], true)"),
    ("d_alias", r"undefined_x | d('z')"),
    ("def_attr_missing", r"users[0].missing | default('m')"),
    ("def_chain_undef", r"undefined_x.a.b | default('m')"),
    ("def_dict_missing_deep", r"d.zz.yy | default('m')"),
    ("def_index_missing", r"lst[10] | default('m')"),
    ("def_no_arg", r"undefined_x | default"),
    ("def_lazy_var", r"tmpl_var | default('m')"),
    # --- join ---
    ("join1", r"strs | join(',')"),
    ("join_nonstr", r"lst | join('-')"),
    ("join_none_elem", r"[1, none_v, true] | join(',')"),
    ("join_attr", r"users | join(', ', attribute='name')"),
    ("join_string", r"'abc' | join('-')"),
    ("join_nosep", r"strs | join"),
    # --- map / select family ---
    ("map_attr", r"users | map(attribute='name') | list"),
    ("map_attr_default", r"users | map(attribute='groups', default=[]) | list"),
    ("map_attr_missing", r"users | map(attribute='groups') | list"),
    ("map_filter", r"strs | map('upper') | list"),
    ("map_filter_args", r"[path_tpl] | map('regex_replace', '^.*/', '') | list"),
    ("map_basename", r"[path_tpl, '/x/y.txt'] | map('basename') | list"),
    ("map_generator", r"users | map(attribute='name')"),
    ("select_truthy", r"[0, 1, '', 'a', none_v, [], [0]] | select | list"),
    ("select_gt", r"lst | select('gt', 1) | list"),
    ("select_sym", r"lst | select('>', 1) | list"),
    ("reject_eq", r"lst | reject('eq', 3) | list"),
    ("selectattr_bool", r"users | selectattr('enabled') | map(attribute='name') | list"),
    ("selectattr_equalto", r"users | selectattr('name', 'equalto', 'bob') | list | length"),
    ("selectattr_defined", r"users | selectattr('groups', 'defined') | map(attribute='name') | list"),
    ("selectattr_contains_missing", r"users | selectattr('groups', 'contains', 'dev') | map(attribute='name') | list"),
    ("rejectattr_in", r"users | rejectattr('name', 'in', ['alice']) | map(attribute='name') | list"),
    ("selectattr_match", r"users | selectattr('name', 'match', '^b') | map(attribute='name') | list"),
    ("selectattr_generator", r"users | selectattr('enabled')"),
    # --- first/last/length/count ---
    ("first_list", r"lst | first"),
    ("last_list", r"lst | last"),
    ("first_str", r"'abc' | first"),
    ("first_empty", r"empty_l | first"),
    ("length_dict", r"d | length"),
    ("length_str", r"unicode_s | length"),
    ("count_list", r"lst | count"),
    ("length_none", r"none_v | length"),
    ("length_gen", r"users | map(attribute='name') | length"),
    # --- case / trim ---
    ("lower1", r"s | lower"),
    ("upper1", r"unicode_s | upper"),
    ("capitalize1", r"'hELLO wORLD' | capitalize"),
    ("title1", r"'hello-world foo_bar o\'neil' | title"),
    ("trim1", r"s_pad | trim"),
    ("trim_chars", r"'xxhixx' | trim('x')"),
    ("trim_int", r"5 | trim"),
    # --- int / float / string / bool ---
    ("int_str", r"int_str | int"),
    ("int_float_str", r"float_str | int"),
    ("int_bad", r"bad_int | int"),
    ("int_bad_default", r"bad_int | int(5)"),
    ("int_hex", r"'0x1A' | int(0, 16)"),
    ("int_hex_base", r"'1A' | int(base=16)"),
    ("int_octal_str", r"'010' | int"),
    ("int_float", r"3.99 | int"),
    ("int_negfloat", r"-3.99 | int"),
    ("int_true", r"true | int"),
    ("int_none", r"none_v | int"),
    ("float_exp", r"'1e3' | float"),
    ("float_bad", r"'x' | float"),
    ("float_int", r"2 | float"),
    ("string_float", r"1.0 | string"),
    ("string_true", r"true | string"),
    ("string_none", r"none_v | string"),
    ("string_dict", r"d | string"),
    ("string_list", r"strs | string"),
    ("bool_yes", r"'yes' | bool"),
    ("bool_on", r"'on' | bool"),
    ("bool_False", r"b_str_false | bool"),
    ("bool_1str", r"'1' | bool"),
    ("bool_foo", r"'foo' | bool"),
    ("bool_y", r"'y' | bool"),
    ("bool_2", r"2 | bool"),
    ("bool_1", r"1 | bool"),
    ("bool_float0", r"0.0 | bool"),
    ("bool_none", r"none_v | bool"),
    ("bool_empty", r"'' | bool"),
    # --- serialisation ---
    ("to_json_d", r"d | to_json"),
    ("to_json_unicode", r"unicode_s | to_json"),
    ("to_json_unicode_noascii", r"unicode_s | to_json(ensure_ascii=false)"),
    ("to_json_users", r"users[1] | to_json"),
    ("to_json_none", r"none_v | to_json"),
    ("to_json_sort", r"d | to_json(sort_keys=true)"),
    ("to_nice_json_d", r"d | to_nice_json"),
    ("to_nice_json_indent2", r"nested1 | to_nice_json(indent=2)"),
    ("to_yaml_d", r"d | to_yaml"),
    ("to_yaml_nested", r"nested1 | to_yaml"),
    ("to_nice_yaml_d", r"d | to_nice_yaml"),
    ("to_nice_yaml_nested", r"users[:2] | to_nice_yaml"),
    ("to_nice_yaml_multiline", r"{'k': multi} | to_nice_yaml"),
    ("to_nice_yaml_indent2", r"nested1 | to_nice_yaml(indent=2)"),
    ("to_yaml_none", r"none_v | to_yaml"),
    ("to_yaml_str", r"'yes' | to_yaml"),
    ("to_nice_yaml_unicode", r"{'k': unicode_s} | to_nice_yaml"),
    ("from_json1", r"'{\"a\": [1, 2]}' | from_json"),
    ("from_yaml1", r"'a: 1\nb: [x, yes]' | from_yaml"),
    # --- combine ---
    ("combine_shallow", r"nested1 | combine(nested2)"),
    ("combine_recursive", r"nested1 | combine(nested2, recursive=true)"),
    ("combine_append", r"nested1 | combine(nested2, recursive=true, list_merge='append')"),
    ("combine_prepend", r"nested1 | combine(nested2, recursive=true, list_merge='prepend')"),
    ("combine_keep", r"nested1 | combine(nested2, recursive=true, list_merge='keep')"),
    ("combine_append_rp", r"{'l': [1, 2, 3]} | combine({'l': [3, 4]}, list_merge='append_rp')"),
    ("combine_list_arg", r"[d, {'c': 3}, {'a': 9}] | combine"),
    ("combine_order", r"d | combine({'c': 3, 'a': 9})"),
    ("combine_none_value", r"d | combine({'a': none_v})"),
    # --- dict/list conversion ---
    ("dict2items1", r"d | dict2items"),
    ("dict2items_names", r"d | dict2items(key_name='k', value_name='v')"),
    ("items2dict1", r"[{'key': 'x', 'value': 1}, {'key': 'y', 'value': 2}] | items2dict"),
    ("items2dict_names", r"users | items2dict(key_name='name', value_name='uid')"),
    ("dictsort1", r"d | dictsort"),
    ("items_method", r"d.items() | list"),
    ("dict_keys_method", r"d.keys() | list"),
    ("items_filter", r"d | items | list"),
    ("list_str", r"'abc' | list"),
    ("list_dict", r"d | list"),
    ("zip1", r"[1, 2, 3] | zip(['a', 'b']) | list"),
    ("zip_longest1", r"[1, 2, 3] | zip_longest(['a'], fillvalue='-') | list"),
    ("zip_gen", r"[1, 2] | zip(['a', 'b'])"),
    ("subelements1", r"users[:2] | subelements('groups') | map('last') | list"),
    # --- set theory / sort / flatten ---
    ("unique1", r"lst | unique"),
    ("union1", r"lst | union([4, 1])"),
    ("difference1", r"lst | difference([1])"),
    ("intersect1", r"lst | intersect([3, 9])"),
    ("symdiff1", r"[1, 2] | symmetric_difference([2, 3])"),
    ("sort1", r"lst | sort"),
    ("sort_strs", r"strs | sort"),
    ("sort_strs_cs", r"strs | sort(case_sensitive=true)"),
    ("sort_reverse", r"lst | sort(reverse=true)"),
    ("sort_attr", r"users | sort(attribute='uid') | map(attribute='name') | list"),
    ("sort_mixed", r"[1, 'a'] | sort"),
    ("flatten1", r"[1, [2, [3, [4]]], none_v] | flatten"),
    ("flatten_levels", r"[1, [2, [3, [4]]]] | flatten(levels=1)"),
    ("reverse_list", r"lst | reverse"),
    ("reverse_list_l", r"lst | reverse | list"),
    ("reverse_str", r"'abc' | reverse"),
    ("max1", r"lst | max"),
    ("min_attr", r"users | min(attribute='uid')"),
    ("sum1", r"lst | sum"),
    ("sum_empty", r"empty_l | sum"),
    ("sum_lists", r"[[1], [2, 3]] | sum(start=[])"),
    ("batch1", r"[1, 2, 3, 4, 5] | batch(2) | list"),
    # --- misc ---
    ("ternary_t", r"true | ternary('y', 'n')"),
    ("ternary_none", r"none_v | ternary('y', 'n', 'null')"),
    ("ternary_str", r"'x' | ternary('y', 'n')"),
    ("ternary_falsestr", r"'false' | ternary('y', 'n')"),
    ("quote1", r"\"it's a b\" | quote"),
    ("quote_simple", r"'simple' | quote"),
    ("quote_empty", r"'' | quote"),
    ("b64encode1", r"'hello' | b64encode"),
    ("b64encode_unicode", r"unicode_s | b64encode"),
    ("b64decode1", r"b64 | b64decode"),
    ("b64decode_bad", r"'x' | b64decode"),
    ("hash_sha1", r"'hello' | hash('sha1')"),
    ("hash_md5", r"'hello' | hash('md5')"),
    ("checksum1", r"'hello' | checksum"),
    ("password_hash_salted", r"'secret' | password_hash('sha512', 'saltsalt')"),
    ("password_hash_unsalted_len", r"('secret' | password_hash('sha512')) | length"),
    ("uuid_ns", r"'example' | to_uuid"),
    ("mandatory_ok", r"'x' | mandatory"),
    ("mandatory_undef", r"undefined_x | mandatory"),
    ("mandatory_msg", r"undefined_x | mandatory('set it')"),
    ("comment_default", r"'hello\nworld' | comment"),
    ("comment_c", r"'hello' | comment('c')"),
    ("comment_cblock", r"'hello' | comment('cblock')"),
    ("comment_erlang", r"'hello' | comment('erlang')"),
    ("comment_xml", r"'hello' | comment('xml')"),
    ("comment_custom", r"'a\nb' | comment(decoration='; ', prefix='', postfix='')"),
    ("indent_default", r"multi | indent"),
    ("indent2", r"multi | indent(2)"),
    ("indent2_first", r"multi | indent(2, true)"),
    ("indent2_first_kw", r"multi | indent(2, first=true, blank=true)"),
    ("indent_str", r"multi | indent('> ')"),
    ("indent_trailing_nl", r"multi_nl | indent(2)"),
    ("center1", r"'ab' | center(7)"),
    ("wordwrap1", r"'the quick brown fox jumps' | wordwrap(10)"),
    ("truncate1", r"'the quick brown fox jumps' | truncate(12)"),
    ("format_filter", r"'%s-%03d' | format('a', 7)"),
    ("percent_op", r"'%s=%s' % ('k', 1)"),
    ("percent_op_single", r"'%05.1f' % f"),
    ("str_format_method", r"'{}-{:>4}'.format('a', 1)"),
    ("human_readable1", r"1048576 | human_readable"),
    ("human_to_bytes1", r"'1.5 MB' | human_to_bytes"),
    ("urlencode_s", r"'a b&c/d' | urlencode"),
    ("urlencode_d", r"d | urlencode"),
    ("urlsplit1", r"'https://u@h.example:8443/p?q=1#f' | urlsplit('port')"),
    ("round1", r"2.5 | round"),
    ("round2", r"3.5 | round"),
    ("round_prec", r"2.675 | round(2)"),
    ("round_floor", r"2.7 | round(0, 'floor')"),
    ("round_ceil", r"1.2 | round(method='ceil')"),
    ("round_int", r"2.4 | round | int"),
    ("abs1", r"neg | abs"),
    ("random_seed", r"[1, 2, 3, 4, 5] | random(seed='x')"),
    ("shuffle_seed", r"[1, 2, 3, 4, 5] | shuffle(seed='x')"),
    ("version_cmp", r"ver is version('2.9', '>')"),
    ("version_filter", r"ver is version_compare('2.10.1', '==')"),
    ("type_debug_s", r"s | type_debug"),
    ("extract1", r"['a', 'b'] | map('extract', {'a': 1, 'b': 2}) | list"),
    ("ipaddr_fqcn", r"cidr | ansible.utils.ipaddr('address')"),
    ("ipaddr_short", r"cidr | ipaddr('address')"),
    ("ipaddr_network", r"cidr | ansible.utils.ipaddr('network')"),
    ("ipaddr_invalid", r"'not-an-ip' | ansible.utils.ipaddr"),
    ("ipv4_list", r"['192.0.2.1', 'x', '2001:db8::1'] | ansible.utils.ipv4"),
    ("splitext_map", r"['a.j2', 'b.conf.j2'] | map('splitext') | map('first') | list"),
    ("path_join1", r"['/etc', 'demo', 'x.conf'] | path_join"),
    ("path_join_abs", r"['/etc', '/abs', 'x'] | path_join"),
    ("realpath_rel", r"'a/../b' | normpath"),
    # --- operators & methods ---
    ("tilde1", r"'a' ~ 1 ~ none_v ~ true"),
    ("tilde_list", r"'a' ~ [1]"),
    ("tilde_nums", r"1 ~ 2"),
    ("plus_str_int", r"'a' + 1"),
    ("plus_lists", r"[1] + [2]"),
    ("plus_strs", r"'a' + 'b'"),
    ("split1", r"csv.split(',')"),
    ("split_ws", r"'  a  b ' .split()"),
    ("split_max", r"s.split(' ', 1)"),
    ("split_filter", r"csv | split(',')"),
    ("startswith1", r"s.startswith('He')"),
    ("startswith_tuple", r"s.startswith(('x', 'H'))"),
    ("endswith1", r"path_tpl.endswith('.j2')"),
    ("strip_method", r"s_pad.strip()"),
    ("upper_method", r"s.upper()"),
    ("join_method", r"'-'.join(strs)"),
    ("dict_get", r"d.get('zz', 'dflt')"),
    ("slice1", r"s[0:5]"),
    ("slice_neg", r"s[-5:]"),
    ("slice_list", r"lst[1:]"),
    ("slice_rev", r"lst[::-1]"),
    ("slice_step", r"s[::2]"),
    ("index_neg", r"lst[-1]"),
    ("in_str", r"'ell' in s"),
    ("in_list", r"3 in lst"),
    ("in_dict", r"'a' in d"),
    ("not_in", r"'x' not in d"),
    ("div1", r"7 / 2"),
    ("div_exact", r"10 / 2"),
    ("floordiv", r"7 // 2"),
    ("floordiv_neg", r"-7 // 2"),
    ("mod_neg", r"-7 % 3"),
    ("pow1", r"2 ** 10"),
    ("pow_neg", r"2 ** -1"),
    ("div_zero", r"1 / 0"),
    ("float_add", r"0.1 + 0.2"),
    ("str_mul", r"'ab' * 3"),
    ("list_mul", r"[1] * 2"),
    ("int_str_add", r"n + int_str | int"),
    ("cmp_str_int", r"'10' > 9"),
    ("cmp_str", r"'10' < '9'"),
    ("range_list", r"range(3) | list"),
    ("range_step", r"range(1, 10, 3) | list"),
    ("range_raw", r"range(3)"),
    ("inline_if", r"'y' if n > 5 else 'n'"),
    ("inline_if_noelse", r"'y' if n < 5"),
    ("and_or", r"none_v or 'fallback'"),
    ("and_val", r"'a' and 'b'"),
    ("not1", r"not empty_l"),
    ("lazy_var", r"tmpl_var"),
    ("lazy_var_upper", r"tmpl_var | upper"),
    ("dict_literal", r"{'b': 1, 'a': none_v, 'c': true}"),
    ("list_literal", r"[1, 'two', none_v, false, 1.5]"),
    ("tuple_literal", r"(1, 2)"),
    ("bool_literal", r"true"),
    ("none_literal", r"none"),
    ("none_var", r"none_v"),
    ("int_literal", r"42"),
    ("str_num_literal", r"'42'"),
    ("str_bool_literal", r"'True'"),
    ("str_list_literal", r"'[1, 2]'"),
    ("float_literal", r"1.50"),
    ("large_int", r"2 ** 70"),
    ("dict_var", r"d"),
    ("list_var", r"strs"),
    ("unicode_var", r"unicode_s"),
    # --- tests ---
    ("t_defined", r"undefined_x is defined"),
    ("t_none_defined", r"none_v is defined"),
    ("t_none", r"none_v is none"),
    ("t_str_seq", r"'abc' is sequence"),
    ("t_str_iter", r"'abc' is iterable"),
    ("t_dict_mapping", r"d is mapping"),
    ("t_bool_number", r"true is number"),
    ("t_bool_integer", r"true is integer"),
    ("t_bool_boolean", r"b_true is boolean"),
    ("t_yes_boolean", r"b_str_yes is boolean"),
    ("t_float_integer", r"2.0 is integer"),
    ("t_str_string", r"'x' is string"),
    ("t_truthy_False", r"'False' is truthy"),
    ("t_truthy_conv", r"'False' is truthy(convert_bool=true)"),
    ("t_falsy_empty", r"empty_d is falsy"),
    ("t_subset", r"[1, 2] is subset([1, 2, 3])"),
    ("t_superset", r"[1, 2, 3] is superset([1])"),
    ("t_contains", r"lst is contains(2)"),
    ("t_in", r"2 is in(lst)"),
    ("t_divisible", r"9 is divisibleby(3)"),
    ("t_even", r"n is even"),
    ("t_lower", r"'abc' is lower"),
    ("t_eq_sym", r"n is eq(7)"),
    ("t_sameas", r"none_v is sameas(none)"),
    ("t_undefined", r"undefined_x is undefined"),
]
