---
dependency:
  name: galaxy
  enabled: false
driver:
  name: default
  options:
    managed: false
platforms:
  - name: instance
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          instance:
            ansible_connection: local
scenario:
  test_sequence: [converge, idempotence, verify]
