package de.terletzkiy.ansibility.semantics.precedence.oracle

import de.terletzkiy.ansibility.semantics.precedence.HashBehaviour
import de.terletzkiy.ansibility.semantics.precedence.PrecedenceEngine
import de.terletzkiy.ansibility.semantics.precedence.PrecedenceEntry
import de.terletzkiy.ansibility.semantics.precedence.VarLayer
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestFactory
import java.io.File

/**
 * The engine must reproduce `ansible-inventory --list` exactly for the synthetic inventories under
 * `inventory-oracle/` (expected outputs generated by `tools/docgen/inventory-oracle/gen.py` with the local
 * ansible-core): every host's variables, every group's hosts and children, and every host's group membership.
 */
class InventoryOracleTest {
    private val root = File(requireNotNull(javaClass.getResource("/inventory-oracle")) { "oracle resources missing" }.toURI())

    private fun caseDirs(): List<File> = root.listFiles().orEmpty().filter { File(it, "oracle.json").isFile }.sortedBy { it.name }

    @Suppress("UNCHECKED_CAST")
    private fun fixture(case: File): Pair<InventoryFixture, Map<String, Any?>> {
        val config = MiniJson.parse(File(case, "oracle.json").readText()) as Map<String, Any?>
        val expected = (MiniJson.parse(File(case, "expected.json").readText()) as Map<String, Any?>)["inventory"] as Map<String, Any?>
        val behaviour = (config["hash_behaviour"] as String?)?.let { requireNotNull(HashBehaviour.parse(it)) } ?: HashBehaviour.REPLACE
        val precedence = (config["precedence"] as String?)?.let { PrecedenceEntry.parse(it).entries } ?: PrecedenceEntry.DEFAULT
        return InventoryFixture(File(case, "inventory/hosts.yml"), case, PrecedenceEngine(behaviour, precedence)) to expected
    }

    @TestFactory
    fun `engine reproduces ansible-inventory for every oracle case`(): List<DynamicTest> {
        val cases = caseDirs()
        assertTrue(cases.size >= 4, "expected at least 4 oracle cases, found ${cases.map { it.name }}")
        return cases.map { case ->
            DynamicTest.dynamicTest(case.name) {
                val (fixture, expected) = fixture(case)
                val mismatches = OracleCompare.mismatches(fixture, expected)
                assertTrue(mismatches.isEmpty(), "${case.name}:\n" + mismatches.joinToString("\n"))
            }
        }
    }

    @Test
    fun `the comparison detects a wrong engine configuration`() {
        val case = File(root, "merge")
        val (right, expected) = fixture(case)
        val wrong = InventoryFixture(right.inventoryFile, case, PrecedenceEngine(HashBehaviour.REPLACE))
        val mismatches = OracleCompare.mismatches(wrong, expected)
        assertTrue(mismatches.any { it.startsWith("m1.config") }, mismatches.joinToString("\n"))
    }

    @Test
    fun `playbook group_vars all beats inventory group_vars all and keeps the shadowed definition`() {
        val (fixture, _) = fixture(File(root, "siblings"))
        val relay = fixture.view("db1")["relay_host"]!!
        assertEquals(VarLayer.PLAYBOOK_GROUP_VARS_ALL, relay.winner.source.layer)
        assertEquals(listOf(VarLayer.INVENTORY_GROUP_VARS_ALL), relay.shadowed.map { it.source.layer })
        assertTrue(relay.winner.source.originId.endsWith("siblings/group_vars/all/vars.yml"))
    }

    @Test
    fun `playbook group_vars of a shallow group beats inventory group_vars of a deeper group`() {
        val (fixture, _) = fixture(File(root, "siblings"))
        val zone = fixture.view("app2")["zone_label"]!!
        assertEquals(VarLayer.PLAYBOOK_GROUP_VARS, zone.winner.source.layer)
        assertEquals(listOf(VarLayer.INVENTORY_GROUP_VARS), zone.shadowed.map { it.source.layer })
    }

    @Test
    fun `sibling groups at the same depth are decided by name`() {
        val (fixture, _) = fixture(File(root, "siblings"))
        val region = fixture.view("app1")["region_name"]!!
        assertTrue(region.winner.source.originId.endsWith("region_us.yml"))
        assertEquals(
            listOf("region_eu.yml", "region.yml"),
            region.shadowed.map { it.source.originId.substringAfterLast('/') },
        )
    }

    @Test
    fun `files of one group directory load in sorted order and the winner is the last one`() {
        val (fixture, _) = fixture(File(root, "siblings"))
        val layered = fixture.view("app1")["layered"]!!
        assertEquals(
            listOf("group_vars/web.yml", "nested/30-deep.yml", "web/20-override.yml", "web/10-base.yml"),
            (listOf(layered.winner) + layered.shadowed).map { it.source.originId.split('/').takeLast(2).joinToString("/") },
        )
    }
}
